name: Go CI Practice

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-ubuntu:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with: 
                go-version: 1.23.4
            
            - name: Install Dependencies
              run: go mod tidy

            - name: Run Tests
              run: go test ./...

            - name: Build Go Binary
              run: go build -o my_app main.go 

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                name: my_app_ubuntu
                path: my_app

            
    build-macos:
        runs-on: macos-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with: 
                go-version: 1.23.4
            
            - name: Install Dependencies
              run: go mod tidy

            - name: Run Tests
              run: go test ./...

            - name: Build Go Binary
              run: go build -o my_app main.go 

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                name: my_app_macos
                path: my_app

    build-windows:
        runs-on: windows-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with: 
                go-version: 1.23.4
            
            - name: Install Dependencies
              run: go mod tidy

            - name: Run Tests
              run: go test ./...

            - name: Build Go Binary
              run: go build -o my_app main.go 

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                name: my_app_windows
                path: my_app

            
            
